language: python
python:
  - "2.7"
env:
#  - TOXENV=py26-1.4
#  - TOXENV=py27-1.4
#  - TOXENV=py26-1.5
  - TOXENV=py27-1.5
install:
  - pip install -q --use-mirrors tox==1.4.2 django-jenkins==0.12.1  pylint==0.25.1 coverage==3.5.2 pep8==0.6.1 psycopg2==2.5 Mock==1.0.1 django-bootstrap-toolkit==2.5.6 factory-boy==2.1.1

before_script:
  - psql -c 'create database django_timepiece;' -U postgres -w
  
script:
  - tox
